### ISSUE TITLE
PL Hackathons

### ISSUE THREAD

**Issue by it09** [bacalhau-project/devrel#47]
- [ ] reach out to Niki about bounties for bacalhau for all her hackathons
so far she mentioned 
- Chainlink hackathon
- FVM despost bacalhau bounty
- ask to ETHTokio bounty and other ETHGlobal 
- [ ] add to them notion hackathon calendar with related info dates/bounties/hackathon theme/etc

**Comment by it09** [comment]
x

**Comment by XandraMcC** [comment]
"we have not put up a Bacalhau bounty in Chainlink (we have skipped that hackathon for this year) due to lack of integration available for FVM and budget constraints"

"there is a $2000 bounty on Decentralized Compute for ETHTokyo"

"Q: are there any bounties on other eth global hackathons?
A: No … we are currently allocating budget to FVM bounties that are more broad in scope"

"Q: So there are no other bounties for decentralised compute?
A: We have tried putting up Bacalhau bounties in the past we don’t get many projects in hackathons. We did it at ETHIndia and couple of other hackathons. But for us an average hackathon has at least 30 projects and big ones have projects in the range of 150-200"

"I am always happy to pass on interesting Bacalhau projects that get built during hackathons ... I see 2-3 projects in every hackathon"

From Niki
